words = (
    "apple", "banana", "orange", "mango", "grape", "pineapple", "strawberry", "blueberry", "kiwi", "watermelon",
    "cat", "dog", "elephant", "tiger", "lion", "zebra", "giraffe", "kangaroo", "koala", "panda",
    "parrot", "eagle", "sparrow", "peacock", "ostrich", "flamingo", "penguin", "dolphin", "whale", "shark",
    "cow", "goat", "sheep", "horse", "buffalo", "donkey", "camel", "rabbit", "deer", "monkey",
    "chicken", "duck", "goose", "turkey", "pigeon", "bat", "crow", "swan", "owl", "woodpecker",
    "rose", "lily", "tulip", "sunflower", "daisy", "orchid", "lotus", "marigold", "jasmine", "lavender",
    "New York", "London", "Paris", "Tokyo", "Beijing", "Sydney", "Berlin", "Rome", "Moscow", "Toronto",
    "Dhaka", "Mumbai", "Dubai", "Seoul", "Bangkok", "Istanbul", "Cairo", "Mexico City", "Los Angeles", "Chicago",
    "Amazon", "Nile", "Ganges", "Yangtze", "Mississippi", "Thames", "Danube", "Volga", "Mekong", "Colorado",
    "Everest", "K2", "Kilimanjaro", "Denali", "Elbrus", "Aconcagua", "Vinson", "McKinley", "Mont Blanc", "Matterhorn",
    "Sahara", "Gobi", "Kalahari", "Thar", "Sonoran", "Atacama", "Arabian", "Mojave", "Namib", "Great Victoria",
    "Asia", "Africa", "Europe", "Australia", "Antarctica", "North America", "South America", "Greenland", "Iceland", "Madagascar",
    "car", "bike", "train", "bus", "airplane", "helicopter", "ship", "boat", "submarine", "tram",
    "computer", "laptop", "tablet", "smartphone", "keyboard", "mouse", "monitor", "printer", "scanner", "speaker",
    "soccer", "basketball", "tennis", "cricket", "hockey", "golf", "volleyball", "baseball", "rugby", "badminton",
    "pizza", "burger", "pasta", "sushi", "tacos", "salad", "steak", "sandwich", "soup", "fries",
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
    "red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "black", "white",
    "circle", "square", "triangle", "rectangle", "pentagon", "hexagon", "octagon", "oval", "diamond", "star",
    "sun", "moon", "planet", "star", "galaxy", "comet", "asteroid", "meteor", "nebula", "black hole",
    "chess", "checkers", "scrabble", "monopoly", "poker", "bridge", "solitaire", "dominoes", "ludo", "carrom"
)
